version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: study_db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: study
      # You can use whatever password you like
      MYSQL_PASSWORD: safe_password
      # Password for root access
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3306:3306
  docker-study-app:
    build: .
    container_name: docker-study-app
    links:
      - db
    image: docker-study-app:latest
    ports:
      - "3000:3000"

